//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tuya.Pagos.Persistence.SqlResources {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SqlFiles {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SqlFiles() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tuya.Pagos.Persistence.SqlResources.SqlFiles", typeof(SqlFiles).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a CREATE DATABASE PAGOS
        ///GO
        ///USE PAGOS
        ///GO
        ///IF NOT EXISTS (SELECT NAME FROM SYS.tables WHERE NAME = &apos;Customer&apos;)
        ///BEGIN
        ///CREATE TABLE Customer (
        ///    IdClient int IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///    Name varchar(50),
        ///    LastName varchar(50),
        ///    Phone varchar(15),
        ///    Email varchar(80),
        ///	Address varchar(100)
        ///);
        ///END
        ///GO
        ///IF NOT EXISTS (SELECT NAME FROM SYS.tables WHERE NAME = &apos;Product&apos;)
        ///BEGIN
        ///CREATE TABLE Product(
        ///	IdProduct int IDENTITY(1,1) NOT NULL PRIMARY KEY,
        ///	Name varchar(150),
        ///	Price int [resto de la cadena truncado]&quot;;.
        /// </summary>
        internal static string InitialMigration {
            get {
                return ResourceManager.GetString("InitialMigration", resourceCulture);
            }
        }
    }
}
